### PR TITLE
Avoid having yet another dotfiles in homedir

### PR DESCRIPTION
**Pull request by jrabinow**
Default to $XDG_CACHE_DIR/sack
Fallback to ~/.cache/sack
Creates directory if non-existant

### CODE REVIEW

**Comment by garaud** [comment]
Thank you for your contribution!

I think it's a good idea.

Can you please just update the README file about the `sack_shortcuts` directory in this section https://github.com/garaud/sack/blob/master/README.md#how-to-configure-it ?

Thanks!

**Review by garaud — CHANGES_REQUESTED** [review]
Looks good to me.

Just update the README file.

**Comment by jrabinow** [comment]
Good catch, I hadn't noticed the reference in the README. Updated.

**Review by garaud — APPROVED** [review]
Perfect. Thanks!

**Pull request merged**
